import { ACTIVITY_ACTIONS, type ActivityAction } from "@/lib/activity/types"
import { AUDIT_ACTIONS, type AuditAction } from "@/lib/audit/types"

/**
 * Compatibility map: legacy `system_audit_log` / AUDIT_ACTIONS → Activity catalog.
 * Infrastructure only — existing audit call sites are NOT rewritten in Fase 3.
 */
export const LEGACY_AUDIT_ACTION_TO_ACTIVITY: Record<AuditAction, ActivityAction> =
  {
    [AUDIT_ACTIONS.CUSTOMER_CREATE]: ACTIVITY_ACTIONS.CUSTOMER_CREATE,
    [AUDIT_ACTIONS.CUSTOMER_UPDATE]: ACTIVITY_ACTIONS.CUSTOMER_UPDATE,
    [AUDIT_ACTIONS.CUSTOMER_VALIDATE]: ACTIVITY_ACTIONS.CUSTOMER_VALIDATE,
    [AUDIT_ACTIONS.CUSTOMER_ACTIVATE]: ACTIVITY_ACTIONS.CUSTOMER_ACTIVATE,
    [AUDIT_ACTIONS.CUSTOMER_ARCHIVE]: ACTIVITY_ACTIONS.CUSTOMER_ARCHIVE,
    [AUDIT_ACTIONS.CUSTOMER_DELETE]: ACTIVITY_ACTIONS.CUSTOMER_DELETE,
    [AUDIT_ACTIONS.CUSTOMER_DELETE_PERMANENT]:
      ACTIVITY_ACTIONS.CUSTOMER_DELETE_PERMANENT,

    [AUDIT_ACTIONS.TASK_CREATE]: ACTIVITY_ACTIONS.TASK_CREATE,
    [AUDIT_ACTIONS.TASK_UPDATE]: ACTIVITY_ACTIONS.TASK_UPDATE,
    [AUDIT_ACTIONS.TASK_ASSIGN_CREW]: ACTIVITY_ACTIONS.TASK_ASSIGN_CREW,
    [AUDIT_ACTIONS.TASK_RESCHEDULE]: ACTIVITY_ACTIONS.TASK_RESCHEDULE,
    [AUDIT_ACTIONS.TASK_STATUS_VENCIDA]: ACTIVITY_ACTIONS.TASK_MARK_OVERDUE,
    [AUDIT_ACTIONS.TASK_STATUS_EN_CURSO]: ACTIVITY_ACTIONS.TASK_START,
    [AUDIT_ACTIONS.TASK_REQUEST_CLOSE]: ACTIVITY_ACTIONS.TASK_SUBMIT_FOR_APPROVAL,
    [AUDIT_ACTIONS.TASK_FINISH]: ACTIVITY_ACTIONS.TASK_APPROVE,
    [AUDIT_ACTIONS.TASK_CLOSE]: ACTIVITY_ACTIONS.TASK_APPROVE,
    [AUDIT_ACTIONS.TASK_DELETE]: ACTIVITY_ACTIONS.TASK_DELETE,
    [AUDIT_ACTIONS.TASK_DELETE_PERMANENT]: ACTIVITY_ACTIONS.TASK_DELETE_PERMANENT,
    [AUDIT_ACTIONS.FORCE_DELETE]: ACTIVITY_ACTIONS.FORCE_DELETE,
    [AUDIT_ACTIONS.PLANNING_CONFIRMED]: ACTIVITY_ACTIONS.PLANNING_CONFIRM,

    [AUDIT_ACTIONS.PROJECT_CREATE]: ACTIVITY_ACTIONS.PROJECT_CREATE,
    [AUDIT_ACTIONS.PROJECT_UPDATE]: ACTIVITY_ACTIONS.PROJECT_UPDATE,
    [AUDIT_ACTIONS.PROJECT_STATUS_CHANGE]: ACTIVITY_ACTIONS.PROJECT_START,
    [AUDIT_ACTIONS.PROJECT_ARCHIVE]: ACTIVITY_ACTIONS.PROJECT_ARCHIVE,
    [AUDIT_ACTIONS.PROJECT_DELETE_PERMANENT]:
      ACTIVITY_ACTIONS.PROJECT_DELETE_PERMANENT,

    [AUDIT_ACTIONS.CONTRACTOR_DELETE_PERMANENT]:
      ACTIVITY_ACTIONS.CONTRACTOR_DELETE_PERMANENT,

    [AUDIT_ACTIONS.EMPLOYEE_CREATE]: ACTIVITY_ACTIONS.EMPLOYEE_CREATE,
    [AUDIT_ACTIONS.EMPLOYEE_UPDATE]: ACTIVITY_ACTIONS.EMPLOYEE_UPDATE,
    [AUDIT_ACTIONS.EMPLOYEE_DEACTIVATE]: ACTIVITY_ACTIONS.EMPLOYEE_DEACTIVATE,
    [AUDIT_ACTIONS.EMPLOYEE_REACTIVATE]: ACTIVITY_ACTIONS.EMPLOYEE_REACTIVATE,
    [AUDIT_ACTIONS.CREW_CREATE]: ACTIVITY_ACTIONS.CREW_CREATE,
    [AUDIT_ACTIONS.CREW_UPDATE]: ACTIVITY_ACTIONS.CREW_UPDATE,
    [AUDIT_ACTIONS.CREW_ARCHIVE]: ACTIVITY_ACTIONS.CREW_ARCHIVE,
    [AUDIT_ACTIONS.CREW_MEMBER_ADD]: ACTIVITY_ACTIONS.CREW_MEMBER_ADD,
    [AUDIT_ACTIONS.CREW_MEMBER_REMOVE]: ACTIVITY_ACTIONS.CREW_MEMBER_REMOVE,
    [AUDIT_ACTIONS.AVAILABILITY_CHANGE]:
      ACTIVITY_ACTIONS.EMPLOYEE_AVAILABILITY_CHANGE,

    [AUDIT_ACTIONS.USER_LOGIN]: ACTIVITY_ACTIONS.USER_LOGIN,
    [AUDIT_ACTIONS.USER_LOGOUT]: ACTIVITY_ACTIONS.USER_LOGOUT,
    [AUDIT_ACTIONS.USER_CREATE]: ACTIVITY_ACTIONS.USER_CREATE,
    [AUDIT_ACTIONS.USER_PROVISION]: ACTIVITY_ACTIONS.USER_PROVISION,
    [AUDIT_ACTIONS.USER_PASSWORD_RESET]: ACTIVITY_ACTIONS.USER_PASSWORD_RESET,
    [AUDIT_ACTIONS.USER_ROLE_CHANGE]: ACTIVITY_ACTIONS.USER_ROLE_CHANGE,
    [AUDIT_ACTIONS.USER_DEACTIVATE]: ACTIVITY_ACTIONS.USER_DEACTIVATE,
    [AUDIT_ACTIONS.USER_REACTIVATE]: ACTIVITY_ACTIONS.USER_REACTIVATE,

    [AUDIT_ACTIONS.MOBILE_DEVICE_REGISTERED]: ACTIVITY_ACTIONS.DEVICE_REGISTER,
    [AUDIT_ACTIONS.MOBILE_DEVICE_ACTIVATED]: ACTIVITY_ACTIONS.DEVICE_ACTIVATE,
    [AUDIT_ACTIONS.MOBILE_DEVICE_BLOCKED]: ACTIVITY_ACTIONS.DEVICE_BLOCK,
    [AUDIT_ACTIONS.SHIFT_STARTED]: ACTIVITY_ACTIONS.SHIFT_START,
    [AUDIT_ACTIONS.SHIFT_FINISHED]: ACTIVITY_ACTIONS.SHIFT_FINISH,

    [AUDIT_ACTIONS.INCIDENT_CREATED]: ACTIVITY_ACTIONS.INCIDENT_CREATE,
    [AUDIT_ACTIONS.INCIDENT_SUPERVISOR_ACTION]:
      ACTIVITY_ACTIONS.INCIDENT_SUPERVISOR_ACTION,
    [AUDIT_ACTIONS.INCIDENT_CLOSED]: ACTIVITY_ACTIONS.INCIDENT_CLOSE,
  }

export function mapLegacyAuditActionToActivity(
  action: AuditAction
): ActivityAction {
  return LEGACY_AUDIT_ACTION_TO_ACTIVITY[action]
}

export function tryMapLegacyAuditActionToActivity(
  action: string
): ActivityAction | null {
  if (Object.prototype.hasOwnProperty.call(LEGACY_AUDIT_ACTION_TO_ACTIVITY, action)) {
    return LEGACY_AUDIT_ACTION_TO_ACTIVITY[action as AuditAction]
  }
  return null
}
