/**
 * Indicator Engine 2.0 — Bespoke Platform 2.0
 * (Sprint 13 — Feature Flags + Shadow Control).
 *
 * Migration control via Feature Flags. Visible UI remains V1 until authorized.
 */

export {
  BUSINESS_INDICATOR_IDS,
  getBusinessIndicator,
  getIndicatorEngineCatalogVersion,
  INDICATOR_ENGINE_CATALOG,
  INDICATOR_ENGINE_DEFINITIONS,
  listBusinessIndicators,
  type RegisteredBusinessIndicatorId,
} from "@/lib/indicator-engine/catalog"

export type {
  BuildExecutiveBriefV2Input,
  BusinessDigest,
  BusinessDigestItem,
  BusinessIndicator,
  BusinessSnapshot,
  DailyIndicatorSnapshot,
  DigestReader,
  ExecutiveBriefMetric,
  ExecutiveBriefOperationalAlert,
  ExecutiveBriefProductionBlock,
  ExecutiveBriefV2,
  ExecutiveBriefV2Builder,
  IndicatorContext,
  SnapshotIdentity,
  SnapshotIdentityLabel,
  SnapshotPayload,
  SnapshotReader,
  SnapshotScope,
  SnapshotTimestamps,
} from "@/lib/indicator-engine/contracts"

export {
  assertBusinessDigestValidInDevelopment,
  validateBusinessDigest,
} from "@/lib/indicator-engine/contracts"

export {
  ACTIVITY_ADAPTER_VERSIONS,
  ACTIVITY_INPUT_METADATA_ALLOWLIST,
  ADAPTER_MODULE_ALIASES,
  activityAdapter,
  activityAdapterV1,
  activityAdapterV2,
  canonicalizeAdapterModule,
  getActivityAdapter,
  mapActivityEngineEventV1ToInput,
  projectBusinessMetadata,
  type ActivityAdapter,
  type ActivityAdapterVersion,
  type ActivityEngineSourceEventV1,
  type ActivityEngineSourceEventV2,
} from "@/lib/indicator-engine/adapters"

export {
  createBrief,
  createDigest,
  createSnapshot,
  DEFAULT_DIGEST_LIMIT,
  executiveBriefV2Builder,
  snapshotEngine,
  assertExecutiveBriefValidInDevelopment,
  validateExecutiveBrief,
  type CreateDigestInput,
  type CreateSnapshotInput,
  type SnapshotEngine,
  type SnapshotEngineBuildInput,
  type SnapshotEngineBuildOutput,
} from "@/lib/indicator-engine/engine"

export {
  createInMemoryActivityProvider,
  DEMO_ACTIVITY_DATASET,
  DEMO_BUSINESS_DATE,
  DEMO_EMPLOYEE_A_ID,
  DEMO_EMPLOYEE_B_ID,
  emptyInMemoryActivityProvider,
  inMemoryActivityProvider,
  stubResolveIndicators,
  type ActivityProvider,
} from "@/lib/indicator-engine/providers"

export {
  clearShadowPipelineMetrics,
  getLastShadowPipelineMetrics,
  getShadowPipelineMetricsSummary,
  listShadowPipelineMetrics,
  observeShadowPipeline,
  runShadowPipeline,
  shadowPipeline,
  type ShadowActivityEvent,
  type ShadowPipelineInput,
  type ShadowPipelineMetrics,
  type ShadowPipelineOutcome,
} from "@/lib/indicator-engine/shadow"

export {
  briefViewFromLegacy,
  briefViewFromV2,
  buildComparisonReport,
  businessDigestComparator,
  compareDigests,
  compareExecutiveBriefs,
  compareSnapshots,
  digestViewFromBusiness,
  digestViewFromLegacyActivity,
  executiveBriefComparator,
  snapshotComparator,
  snapshotViewFromBusiness,
  snapshotViewFromLegacy,
  type BuildComparisonReportInput,
  type ComparableBriefView,
  type ComparableDigestItem,
  type ComparableDigestView,
  type ComparableIndicatorMap,
  type ComparableMetric,
  type ComparableProductionBlock,
  type ComparableSnapshotView,
  type ComparisonIssue,
  type ComparisonReport,
  type ComparisonTolerance,
  type FieldComparisonResult,
  type LegacyExecutiveBriefLike,
  type LegacyIndicatorSnapshotLike,
} from "@/lib/indicator-engine/comparator"

export {
  clearIndicatorEngineFeatureFlagsOverride,
  DEFAULT_INDICATOR_ENGINE_FEATURE_FLAGS,
  getIndicatorEngineFeatureFlags,
  INDICATOR_ENGINE_MODES,
  indicatorEngineFeatureFlags,
  isComparatorEnabled,
  isShadowPipelineEnabled,
  isTelemetryEnabled,
  resolveVisibleEngineMode,
  setIndicatorEngineFeatureFlagsOverride,
  shouldRunDualReadSidePath,
  type IndicatorEngineFeatureFlags,
  type IndicatorEngineFeatureFlagsPartial,
  type IndicatorEngineMode,
} from "@/lib/indicator-engine/feature-flags"

export {
  createIndicatorFacade,
  DEFAULT_INDICATOR_FACADE_CONFIG,
  getDefaultIndicatorFacadeConfig,
  INDICATOR_FACADE_BACKENDS,
  indicatorFacade,
  resolveIndicatorFacadeBackend,
  clearSituationRoomDualReadState,
  getLastSituationRoomDualReadState,
  loadSituationRoomViaDualRead,
  canServeSnapshotOfficialBrief,
  resolveOfficialSituationRoomBrief,
  projectSnapshotBriefToExecutiveBrief,
  type BuildExecutiveBriefInput as FacadeBuildExecutiveBriefInput,
  type ExecutiveBrief as FacadeExecutiveBrief,
  type IndicatorFacade,
  type IndicatorFacadeBackend,
  type IndicatorFacadeConfig,
  type IndicatorFacadeDigest,
  type IndicatorFacadeFeatureFlags,
  type IndicatorSnapshot as FacadeIndicatorSnapshot,
  type IndicatorSourceEvent as FacadeIndicatorSourceEvent,
  type OfficialSituationRoomBriefResult,
  type OfficialSituationRoomSource,
  type SituationRoomDualReadInput,
  type SituationRoomDualReadResult,
} from "@/lib/indicator-engine/facade"

export {
  clearPerformanceReports,
  getLastPerformanceReport,
  getPerformanceTelemetrySummary,
  hookComparatorTelemetry,
  hookFacadeGetBrief,
  hookFacadeGetDigest,
  hookFacadeGetSnapshot,
  hookShadowPipelineTelemetry,
  isPerformanceTelemetryEnabled,
  listPerformanceReports,
  measureTelemetryStage,
  performanceTelemetry,
  startPerformanceTelemetry,
  TELEMETRY_SOURCES,
  TELEMETRY_STAGES,
  type PerformanceReport,
  type PerformanceTelemetrySession,
  type TelemetrySource,
  type TelemetryStage,
} from "@/lib/indicator-engine/telemetry"

export {
  activityInputStage,
  assertActivityInputValidInDevelopment,
  assertPipelineContextValidInDevelopment,
  assertPipelineResultValidInDevelopment,
  briefBuilderStage,
  digestBuilderStage,
  getIndicatorPipelineStageDescriptor,
  INDICATOR_PIPELINE_STAGE_CONTRACTS,
  INDICATOR_PIPELINE_STAGE_DESCRIPTORS,
  INDICATOR_PIPELINE_STAGES,
  indicatorPipeline,
  indicatorPipelineDefinition,
  indicatorResolutionStage,
  inMemoryPipelineRunner,
  isIndicatorPipelineStage,
  listIndicatorPipelineStages,
  normalizeStage,
  outputStage,
  runInMemoryPipeline,
  snapshotBuilderStage,
  validateActivityInput,
  validatePipelineContext,
  validatePipelineResult,
  type ActivityInput,
  type ActivityInputEvent,
  type BriefBuilderInput,
  type BriefBuilderOutput,
  type DigestBuilderInput,
  type DigestBuilderOutput,
  type IndicatorPipeline,
  type IndicatorPipelineDefinition,
  type IndicatorPipelineRunner,
  type IndicatorPipelineStage,
  type IndicatorResolutionInput,
  type IndicatorResolutionOutput,
  type InMemoryPipelineRunInput,
  type InMemoryPipelineRunOutput,
  type NormalizeInput,
  type NormalizeOutput,
  type NormalizedActivityFact,
  type PipelineContext,
  type PipelineIssue,
  type PipelineOutput,
  type PipelineResult,
  type PipelineStageContract,
  type PipelineStageDescriptor,
  type SnapshotBuilderInput,
  type SnapshotBuilderOutput,
} from "@/lib/indicator-engine/pipeline"

export {
  buildIndicatorRegistry,
  createIndicatorRegistryBuilder,
  INDICATOR_ENGINE_CATALOG_VERSION,
  indicatorRegistry,
  validateIndicatorRegistryDefinitions,
  type IndicatorRegistry,
  type IndicatorRegistryBuilder,
} from "@/lib/indicator-engine/registry"

export {
  assertBusinessSnapshotValidInDevelopment,
  getSnapshotScopeTier,
  isSnapshotScope,
  isSnapshotStatus,
  SNAPSHOT_SCOPE_TIERS,
  SNAPSHOT_SCOPES,
  SNAPSHOT_SCOPES_P0,
  SNAPSHOT_SCOPES_P1,
  SNAPSHOT_STATUSES,
  SNAPSHOT_UPDATE_MODES,
  snapshotScopeRequiresSubject,
  validateBusinessSnapshot,
  validateSnapshotIdentity,
  validateSnapshotPayload,
  type SnapshotScopeTier,
  type SnapshotStatus,
  type SnapshotUpdateMode,
} from "@/lib/indicator-engine/snapshot"

export type {
  BusinessDate,
  BusinessIndicatorCategory,
  BusinessIndicatorId,
  BusinessIndicatorOrigin,
  BusinessIndicatorOwner,
  BusinessIndicatorStatus,
  IndicatorAnalysisUnit,
  IndicatorMeasureUnit,
  IndicatorValue,
} from "@/lib/indicator-engine/types"

export {
  BUSINESS_INDICATOR_CATEGORIES,
  BUSINESS_INDICATOR_ORIGINS,
  BUSINESS_INDICATOR_OWNERS,
  BUSINESS_INDICATOR_STATUSES,
} from "@/lib/indicator-engine/types"

export { assertNever } from "@/lib/indicator-engine/utils"
