import { ACTIVITY_EVENT_ACTIONS } from "@/lib/activity/actions"
import { ACTIVITY_ACTIONS as LEGACY_CS_ACTIONS } from "@/lib/activity-engine/activity-actions"
import type { BusinessIndicator } from "@/lib/indicator-engine/contracts/business-indicator"
import type { IndicatorAnalysisUnit } from "@/lib/indicator-engine/types/analysis-unit"

/**
 * Stable ids for Indicator Engine 2.0 Registry.
 * Mirrored from `@/lib/indicators` INDICATOR_IDS — do not delete the legacy catalog.
 */
export const BUSINESS_INDICATOR_IDS = {
  EVENTS_TOTAL: "events_total",
  FIRST_EVENT_AT: "first_event_at",
  LAST_EVENT_AT: "last_event_at",
  ACTIVE_TIME_MS: "active_time_ms",
  DISTINCT_MODULES: "distinct_modules",
  EMPLOYEES_ACTIVE: "employees_active",
  CREWS_ACTIVE: "crews_active",
  PROJECTS_ACTIVE: "projects_active",

  CUSTOMERS_CREATED: "customers_created",
  CUSTOMERS_UPDATED: "customers_updated",

  ATTENTIONS_CREATED: "attentions_created",
  ATTENTIONS_RESOLVED: "attentions_resolved",
  ATTENTIONS_TRANSFERRED: "attentions_transferred",
  ATTENTIONS_WORKORDERS_GENERATED: "attentions_workorders_generated",
  RETENTIONS: "retentions",

  REQUESTS_CREATED: "requests_created",
  REQUESTS_RESOLVED: "requests_resolved",
  COMMERCIAL_ACTIVITIES: "commercial_activities",
  COMMERCIAL_COMPLETED: "commercial_completed",

  WORKORDERS_CREATED: "workorders_created",
  WORKORDERS_ASSIGNED: "workorders_assigned",
  WORKORDERS_STARTED: "workorders_started",
  WORKORDERS_FINISHED: "workorders_finished",
  WORKORDERS_RESCHEDULED: "workorders_rescheduled",
  WORKORDERS_CANCELLED: "workorders_cancelled",

  PROJECTS_CREATED: "projects_created",
  PROJECTS_UPDATED: "projects_updated",
  PROJECTS_STARTED: "projects_started",
  PROJECTS_FINISHED: "projects_finished",

  SETTINGS_UPDATED: "settings_updated",

  BUCKET_CUSTOMERS: "bucket_customers",
  BUCKET_REQUESTS: "bucket_requests",
  BUCKET_WORK_ORDERS: "bucket_work_orders",
  BUCKET_ATTENTIONS: "bucket_attentions",
  BUCKET_COMMERCIAL: "bucket_commercial",
  BUCKET_PROJECTS: "bucket_projects",
  BUCKET_SETTINGS: "bucket_settings",
} as const

export type RegisteredBusinessIndicatorId =
  (typeof BUSINESS_INDICATOR_IDS)[keyof typeof BUSINESS_INDICATOR_IDS]

const ALL_UNITS = [
  "employee",
  "crew",
  "project",
  "customer",
  "company",
] as const satisfies readonly IndicatorAnalysisUnit[]

const EMPLOYEE_COMPANY = [
  "employee",
  "company",
] as const satisfies readonly IndicatorAnalysisUnit[]

const EMPLOYEE_CREW_COMPANY = [
  "employee",
  "crew",
  "company",
] as const satisfies readonly IndicatorAnalysisUnit[]

const PROJECT_COMPANY = [
  "project",
  "company",
  "employee",
] as const satisfies readonly IndicatorAnalysisUnit[]

const CUSTOMER_COMPANY = [
  "customer",
  "company",
  "employee",
] as const satisfies readonly IndicatorAnalysisUnit[]

const DEFINITION_VERSION = "1.0.0"

const OWNER = "indicator-engine" as const
const ORIGIN = "activity_events" as const

/**
 * Migrated catalog from `@/lib/indicators` → Indicator Engine 2.0 Registry.
 * Legacy catalog remains the live source for `@/lib/indicators` compute.
 */
export const INDICATOR_ENGINE_DEFINITIONS: readonly BusinessIndicator[] = [
  {
    id: BUSINESS_INDICATOR_IDS.EVENTS_TOTAL,
    name: "Eventos totales",
    description: "Cantidad total de eventos de actividad en el período.",
    category: "meta",
    unit: "count",
    scope: ALL_UNITS,
    version: DEFINITION_VERSION,
    status: "active",
    owner: OWNER,
    origin: ORIGIN,
    calculation: "count_matching_events",
  },
  {
    id: BUSINESS_INDICATOR_IDS.FIRST_EVENT_AT,
    name: "Primer evento",
    description: "Marca temporal del primer evento del período.",
    category: "meta",
    unit: "timestamp_iso",
    scope: ALL_UNITS,
    version: DEFINITION_VERSION,
    status: "active",
    owner: OWNER,
    origin: ORIGIN,
    calculation: "min_created_at",
  },
  {
    id: BUSINESS_INDICATOR_IDS.LAST_EVENT_AT,
    name: "Último evento",
    description: "Marca temporal del último evento del período.",
    category: "meta",
    unit: "timestamp_iso",
    scope: ALL_UNITS,
    version: DEFINITION_VERSION,
    status: "active",
    owner: OWNER,
    origin: ORIGIN,
    calculation: "max_created_at",
  },
  {
    id: BUSINESS_INDICATOR_IDS.ACTIVE_TIME_MS,
    name: "Tiempo activo",
    description:
      "Intervalo entre el primer y el último evento del período (aprox. jornada).",
    category: "meta",
    unit: "milliseconds",
    scope: EMPLOYEE_COMPANY,
    version: DEFINITION_VERSION,
    status: "active",
    owner: OWNER,
    origin: ORIGIN,
    calculation: "span_first_to_last_ms",
  },
  {
    id: BUSINESS_INDICATOR_IDS.DISTINCT_MODULES,
    name: "Módulos distintos",
    description: "Cantidad de módulos canónicos con al menos un evento.",
    category: "meta",
    unit: "count",
    scope: EMPLOYEE_COMPANY,
    version: DEFINITION_VERSION,
    status: "active",
    owner: OWNER,
    origin: ORIGIN,
    calculation: "count_distinct_canonical_modules",
  },
  {
    id: BUSINESS_INDICATOR_IDS.EMPLOYEES_ACTIVE,
    name: "Empleados activos",
    description: "Empleados distintos con al menos un evento en el período.",
    category: "meta",
    unit: "count",
    scope: ["company", "crew", "project"],
    version: DEFINITION_VERSION,
    status: "active",
    owner: OWNER,
    origin: ORIGIN,
    calculation: "count_distinct_employee_ids",
  },
  {
    id: BUSINESS_INDICATOR_IDS.CREWS_ACTIVE,
    name: "Cuadrillas activas",
    description: "Cuadrillas distintas con actividad en el período.",
    category: "meta",
    unit: "count",
    scope: ["company", "employee"],
    version: DEFINITION_VERSION,
    status: "active",
    owner: OWNER,
    origin: ORIGIN,
    calculation: "count_distinct_entity_ids",
    entityTypes: ["crew"],
  },
  {
    id: BUSINESS_INDICATOR_IDS.PROJECTS_ACTIVE,
    name: "Obras activas",
    description: "Obras distintas con actividad en el período.",
    category: "meta",
    unit: "count",
    scope: ["company", "employee", "crew"],
    version: DEFINITION_VERSION,
    status: "active",
    owner: OWNER,
    origin: ORIGIN,
    calculation: "count_distinct_entity_ids",
    entityTypes: ["project"],
  },

  {
    id: BUSINESS_INDICATOR_IDS.CUSTOMERS_CREATED,
    name: "Clientes nuevos",
    description: "Clientes creados en el período.",
    category: "customers",
    unit: "count",
    scope: CUSTOMER_COMPANY,
    version: DEFINITION_VERSION,
    status: "active",
    owner: OWNER,
    origin: ORIGIN,
    calculation: "count_matching_events",
    actions: [ACTIVITY_EVENT_ACTIONS.CUSTOMER_CREATED],
  },
  {
    id: BUSINESS_INDICATOR_IDS.CUSTOMERS_UPDATED,
    name: "Clientes modificados",
    description:
      "Actualizaciones, archivo, reactivación o etiquetas de clientes.",
    category: "customers",
    unit: "count",
    scope: CUSTOMER_COMPANY,
    version: DEFINITION_VERSION,
    status: "active",
    owner: OWNER,
    origin: ORIGIN,
    calculation: "count_matching_events",
    actions: [
      ACTIVITY_EVENT_ACTIONS.CUSTOMER_UPDATED,
      ACTIVITY_EVENT_ACTIONS.CUSTOMER_ARCHIVED,
      ACTIVITY_EVENT_ACTIONS.CUSTOMER_REACTIVATED,
      ACTIVITY_EVENT_ACTIONS.CUSTOMER_TAG_CHANGED,
    ],
  },

  {
    id: BUSINESS_INDICATOR_IDS.ATTENTIONS_CREATED,
    name: "Consultas / atenciones creadas",
    description: "Expedientes o atenciones abiertas (canónico + legado CS).",
    category: "attention",
    unit: "count",
    scope: CUSTOMER_COMPANY,
    version: DEFINITION_VERSION,
    status: "active",
    owner: OWNER,
    origin: ORIGIN,
    calculation: "count_matching_events",
    actions: [
      ACTIVITY_EVENT_ACTIONS.ATTENTION_CREATED,
      LEGACY_CS_ACTIONS.CASE_CREATED,
    ],
  },
  {
    id: BUSINESS_INDICATOR_IDS.ATTENTIONS_RESOLVED,
    name: "Consultas resueltas",
    description: "Atenciones o expedientes cerrados / resueltos.",
    category: "attention",
    unit: "count",
    scope: CUSTOMER_COMPANY,
    version: DEFINITION_VERSION,
    status: "active",
    owner: OWNER,
    origin: ORIGIN,
    calculation: "count_matching_events",
    actions: [
      ACTIVITY_EVENT_ACTIONS.ATTENTION_RESOLVED,
      LEGACY_CS_ACTIONS.CASE_CLOSED,
    ],
  },
  {
    id: BUSINESS_INDICATOR_IDS.ATTENTIONS_TRANSFERRED,
    name: "Atenciones transferidas / derivadas",
    description: "Transferencias canónicas y derivaciones de Customer Service.",
    category: "attention",
    unit: "count",
    scope: CUSTOMER_COMPANY,
    version: DEFINITION_VERSION,
    status: "active",
    owner: OWNER,
    origin: ORIGIN,
    calculation: "count_matching_events",
    actions: [
      ACTIVITY_EVENT_ACTIONS.ATTENTION_TRANSFERRED,
      LEGACY_CS_ACTIONS.DERIVATION_CREATED,
    ],
  },
  {
    id: BUSINESS_INDICATOR_IDS.ATTENTIONS_WORKORDERS_GENERATED,
    name: "OT generadas desde atención",
    description: "Órdenes de trabajo generadas desde atención al cliente.",
    category: "attention",
    unit: "count",
    scope: CUSTOMER_COMPANY,
    version: DEFINITION_VERSION,
    status: "active",
    owner: OWNER,
    origin: ORIGIN,
    calculation: "count_matching_events",
    actions: [
      ACTIVITY_EVENT_ACTIONS.ATTENTION_WORKORDER_GENERATED,
      LEGACY_CS_ACTIONS.OT_CREATED,
    ],
  },
  {
    id: BUSINESS_INDICATOR_IDS.RETENTIONS,
    name: "Retenciones",
    description:
      "Cambios de próximo paso a retención comercial (realizar_retencion).",
    category: "attention",
    unit: "count",
    scope: CUSTOMER_COMPANY,
    version: DEFINITION_VERSION,
    status: "active",
    owner: OWNER,
    origin: ORIGIN,
    calculation: "count_matching_events",
    actions: [LEGACY_CS_ACTIONS.NEXT_STEP_CHANGED],
    metadataEquals: { new_next_step: "realizar_retencion" },
  },

  {
    id: BUSINESS_INDICATOR_IDS.REQUESTS_CREATED,
    name: "Solicitudes creadas",
    description: "Solicitudes comerciales creadas.",
    category: "commercial",
    unit: "count",
    scope: CUSTOMER_COMPANY,
    version: DEFINITION_VERSION,
    status: "active",
    owner: OWNER,
    origin: ORIGIN,
    calculation: "count_matching_events",
    actions: [ACTIVITY_EVENT_ACTIONS.REQUEST_CREATED],
  },
  {
    id: BUSINESS_INDICATOR_IDS.REQUESTS_RESOLVED,
    name: "Solicitudes resueltas",
    description: "Solicitudes comerciales resueltas.",
    category: "commercial",
    unit: "count",
    scope: CUSTOMER_COMPANY,
    version: DEFINITION_VERSION,
    status: "active",
    owner: OWNER,
    origin: ORIGIN,
    calculation: "count_matching_events",
    actions: [ACTIVITY_EVENT_ACTIONS.REQUEST_RESOLVED],
  },
  {
    id: BUSINESS_INDICATOR_IDS.COMMERCIAL_ACTIVITIES,
    name: "Actividades comerciales",
    description: "Alta, edición, baja o cierre de actividades comerciales.",
    category: "commercial",
    unit: "count",
    scope: EMPLOYEE_COMPANY,
    version: DEFINITION_VERSION,
    status: "active",
    owner: OWNER,
    origin: ORIGIN,
    calculation: "count_matching_events",
    actions: [
      ACTIVITY_EVENT_ACTIONS.COMMERCIAL_ACTIVITY_CREATED,
      ACTIVITY_EVENT_ACTIONS.COMMERCIAL_ACTIVITY_UPDATED,
      ACTIVITY_EVENT_ACTIONS.COMMERCIAL_ACTIVITY_DELETED,
      ACTIVITY_EVENT_ACTIONS.COMMERCIAL_ACTIVITY_COMPLETED,
    ],
  },
  {
    id: BUSINESS_INDICATOR_IDS.COMMERCIAL_COMPLETED,
    name: "Ventas realizadas",
    description: "Actividades comerciales completadas.",
    category: "commercial",
    unit: "count",
    scope: EMPLOYEE_COMPANY,
    version: DEFINITION_VERSION,
    status: "active",
    owner: OWNER,
    origin: ORIGIN,
    calculation: "count_matching_events",
    actions: [ACTIVITY_EVENT_ACTIONS.COMMERCIAL_ACTIVITY_COMPLETED],
  },

  {
    id: BUSINESS_INDICATOR_IDS.WORKORDERS_CREATED,
    name: "OT creadas",
    description: "Órdenes de trabajo creadas.",
    category: "workorders",
    unit: "count",
    scope: EMPLOYEE_CREW_COMPANY,
    version: DEFINITION_VERSION,
    status: "active",
    owner: OWNER,
    origin: ORIGIN,
    calculation: "count_matching_events",
    actions: [ACTIVITY_EVENT_ACTIONS.WORKORDER_CREATED],
  },
  {
    id: BUSINESS_INDICATOR_IDS.WORKORDERS_ASSIGNED,
    name: "OT asignadas",
    description: "Órdenes de trabajo asignadas a cuadrilla.",
    category: "workorders",
    unit: "count",
    scope: EMPLOYEE_CREW_COMPANY,
    version: DEFINITION_VERSION,
    status: "active",
    owner: OWNER,
    origin: ORIGIN,
    calculation: "count_matching_events",
    actions: [ACTIVITY_EVENT_ACTIONS.WORKORDER_ASSIGNED],
  },
  {
    id: BUSINESS_INDICATOR_IDS.WORKORDERS_STARTED,
    name: "OT iniciadas",
    description: "Órdenes de trabajo iniciadas.",
    category: "workorders",
    unit: "count",
    scope: EMPLOYEE_CREW_COMPANY,
    version: DEFINITION_VERSION,
    status: "active",
    owner: OWNER,
    origin: ORIGIN,
    calculation: "count_matching_events",
    actions: [ACTIVITY_EVENT_ACTIONS.WORKORDER_STARTED],
  },
  {
    id: BUSINESS_INDICATOR_IDS.WORKORDERS_FINISHED,
    name: "OT finalizadas",
    description: "Órdenes de trabajo finalizadas.",
    category: "workorders",
    unit: "count",
    scope: EMPLOYEE_CREW_COMPANY,
    version: DEFINITION_VERSION,
    status: "active",
    owner: OWNER,
    origin: ORIGIN,
    calculation: "count_matching_events",
    actions: [ACTIVITY_EVENT_ACTIONS.WORKORDER_FINISHED],
  },
  {
    id: BUSINESS_INDICATOR_IDS.WORKORDERS_RESCHEDULED,
    name: "OT reprogramadas",
    description: "Órdenes de trabajo reprogramadas.",
    category: "workorders",
    unit: "count",
    scope: EMPLOYEE_CREW_COMPANY,
    version: DEFINITION_VERSION,
    status: "active",
    owner: OWNER,
    origin: ORIGIN,
    calculation: "count_matching_events",
    actions: [ACTIVITY_EVENT_ACTIONS.WORKORDER_RESCHEDULED],
  },
  {
    id: BUSINESS_INDICATOR_IDS.WORKORDERS_CANCELLED,
    name: "OT canceladas",
    description: "Órdenes de trabajo canceladas.",
    category: "workorders",
    unit: "count",
    scope: EMPLOYEE_CREW_COMPANY,
    version: DEFINITION_VERSION,
    status: "active",
    owner: OWNER,
    origin: ORIGIN,
    calculation: "count_matching_events",
    actions: [ACTIVITY_EVENT_ACTIONS.WORKORDER_CANCELLED],
  },

  {
    id: BUSINESS_INDICATOR_IDS.PROJECTS_CREATED,
    name: "Obras creadas",
    description: "Obras dadas de alta.",
    category: "projects",
    unit: "count",
    scope: PROJECT_COMPANY,
    version: DEFINITION_VERSION,
    status: "active",
    owner: OWNER,
    origin: ORIGIN,
    calculation: "count_matching_events",
    actions: [ACTIVITY_EVENT_ACTIONS.PROJECT_CREATED],
  },
  {
    id: BUSINESS_INDICATOR_IDS.PROJECTS_UPDATED,
    name: "Obras modificadas",
    description: "Cambios de estado, datos o supervisor de obras.",
    category: "projects",
    unit: "count",
    scope: PROJECT_COMPANY,
    version: DEFINITION_VERSION,
    status: "active",
    owner: OWNER,
    origin: ORIGIN,
    calculation: "count_matching_events",
    actions: [
      ACTIVITY_EVENT_ACTIONS.PROJECT_UPDATED,
      ACTIVITY_EVENT_ACTIONS.PROJECT_STARTED,
      ACTIVITY_EVENT_ACTIONS.PROJECT_PAUSED,
      ACTIVITY_EVENT_ACTIONS.PROJECT_FINISHED,
      ACTIVITY_EVENT_ACTIONS.PROJECT_SUPERVISOR_CHANGED,
    ],
  },
  {
    id: BUSINESS_INDICATOR_IDS.PROJECTS_STARTED,
    name: "Obras iniciadas",
    description: "Obras que iniciaron ejecución.",
    category: "projects",
    unit: "count",
    scope: PROJECT_COMPANY,
    version: DEFINITION_VERSION,
    status: "active",
    owner: OWNER,
    origin: ORIGIN,
    calculation: "count_matching_events",
    actions: [ACTIVITY_EVENT_ACTIONS.PROJECT_STARTED],
  },
  {
    id: BUSINESS_INDICATOR_IDS.PROJECTS_FINISHED,
    name: "Obras finalizadas",
    description: "Obras finalizadas.",
    category: "projects",
    unit: "count",
    scope: PROJECT_COMPANY,
    version: DEFINITION_VERSION,
    status: "active",
    owner: OWNER,
    origin: ORIGIN,
    calculation: "count_matching_events",
    actions: [ACTIVITY_EVENT_ACTIONS.PROJECT_FINISHED],
  },

  {
    id: BUSINESS_INDICATOR_IDS.SETTINGS_UPDATED,
    name: "Configuraciones",
    description: "Cambios de catálogos / configuración.",
    category: "settings",
    unit: "count",
    scope: ["company", "employee"],
    version: DEFINITION_VERSION,
    status: "active",
    owner: OWNER,
    origin: ORIGIN,
    calculation: "count_matching_events",
    actions: [
      ACTIVITY_EVENT_ACTIONS.CATALOG_CREATED,
      ACTIVITY_EVENT_ACTIONS.CATALOG_UPDATED,
      ACTIVITY_EVENT_ACTIONS.CATALOG_DELETED,
    ],
  },

  {
    id: BUSINESS_INDICATOR_IDS.BUCKET_CUSTOMERS,
    name: "Actividad de clientes (bucket)",
    description: "Eventos del módulo customers (transicional).",
    category: "transitional",
    unit: "count",
    scope: ALL_UNITS,
    version: DEFINITION_VERSION,
    status: "transitional",
    owner: OWNER,
    origin: ORIGIN,
    calculation: "count_matching_events",
    modules: ["customers"],
  },
  {
    id: BUSINESS_INDICATOR_IDS.BUCKET_REQUESTS,
    name: "Actividad de solicitudes (bucket)",
    description: "Eventos del módulo requests (transicional).",
    category: "transitional",
    unit: "count",
    scope: ALL_UNITS,
    version: DEFINITION_VERSION,
    status: "transitional",
    owner: OWNER,
    origin: ORIGIN,
    calculation: "count_matching_events",
    modules: ["requests"],
  },
  {
    id: BUSINESS_INDICATOR_IDS.BUCKET_WORK_ORDERS,
    name: "Actividad de OT / planificación (bucket)",
    description: "Eventos de tasks y planning (transicional).",
    category: "transitional",
    unit: "count",
    scope: ALL_UNITS,
    version: DEFINITION_VERSION,
    status: "transitional",
    owner: OWNER,
    origin: ORIGIN,
    calculation: "count_matching_events",
    modules: ["tasks", "planning"],
  },
  {
    id: BUSINESS_INDICATOR_IDS.BUCKET_ATTENTIONS,
    name: "Actividad de atención (bucket)",
    description:
      "Eventos del módulo atencion (incluye alias customer_service).",
    category: "transitional",
    unit: "count",
    scope: ALL_UNITS,
    version: DEFINITION_VERSION,
    status: "transitional",
    owner: OWNER,
    origin: ORIGIN,
    calculation: "count_matching_events",
    modules: ["atencion"],
  },
  {
    id: BUSINESS_INDICATOR_IDS.BUCKET_COMMERCIAL,
    name: "Actividad comercial (bucket)",
    description: "Eventos del módulo commercial (incluye alias sales).",
    category: "transitional",
    unit: "count",
    scope: ALL_UNITS,
    version: DEFINITION_VERSION,
    status: "transitional",
    owner: OWNER,
    origin: ORIGIN,
    calculation: "count_matching_events",
    modules: ["commercial"],
  },
  {
    id: BUSINESS_INDICATOR_IDS.BUCKET_PROJECTS,
    name: "Actividad de obras (bucket)",
    description: "Eventos del módulo projects (transicional).",
    category: "transitional",
    unit: "count",
    scope: ALL_UNITS,
    version: DEFINITION_VERSION,
    status: "transitional",
    owner: OWNER,
    origin: ORIGIN,
    calculation: "count_matching_events",
    modules: ["projects"],
  },
  {
    id: BUSINESS_INDICATOR_IDS.BUCKET_SETTINGS,
    name: "Actividad de configuración (bucket)",
    description: "Eventos del módulo settings (transicional).",
    category: "transitional",
    unit: "count",
    scope: ALL_UNITS,
    version: DEFINITION_VERSION,
    status: "transitional",
    owner: OWNER,
    origin: ORIGIN,
    calculation: "count_matching_events",
    modules: ["settings"],
  },
]
