/**
 * Lean Mobile agenda task columns (Sprint 18).
 * Omits heavy unused blobs (checklist, operational_steps, description, …).
 * Public Mobile JSON contracts unchanged — only internal SELECT.
 */

export const MOBILE_AGENDA_TASK_SELECT = [
  "id",
  "code",
  "title",
  "type",
  "status",
  "priority",
  "work_order_number",
  "due_date",
  "scheduled_time",
  "customer_name",
  "project_name",
  "service_address",
  "locality",
  "observations_for_crew",
  "amount_to_collect",
  "latitude",
  "longitude",
  "execution_order",
  "dispatch_order",
  "crew_id",
  "crew",
  "task_metadata",
  "service_type",
].join(", ")

/** Columns never requested for agenda list / nextWork reuse. */
export const MOBILE_AGENDA_TASK_OMITTED_COLUMNS = [
  "checklist",
  "operational_steps",
  "description",
  "cancellation_observation",
  "cancellation_reason",
  "incident_observation",
  "incident_reason",
  "incident_reported_at",
  "incident_reported_by",
  "rejection_reason",
  "reschedule_notes",
  "reschedule_reason",
  "rescheduled_at",
  "rescheduled_by",
  "shared_location",
  "location_resolution_method",
  "progress",
  "estimated_duration",
  "installation_cost",
  "payment_method",
  "customer_dni",
  "customer_id",
  "customer_company",
  "customer_phone",
  "project_id",
  "project_code",
  "start_date",
  "completed_at",
  "closed_at",
  "updated_at",
  "created_at",
  "supervisor",
  "contracted_plan",
  "original_scheduled_date",
  "original_scheduled_time",
] as const
