import { ACTIVITY_EVENT_ACTIONS } from "@/lib/activity/actions"
import { ACTIVITY_ACTIONS as LEGACY_CS_ACTIONS } from "@/lib/activity-engine/activity-actions"

/** Actions shown in “Actividad relevante” (evidence, not full feed). */
export const EXECUTIVE_RELEVANT_ACTIONS = new Set<string>([
  ACTIVITY_EVENT_ACTIONS.WORKORDER_FINISHED,
  ACTIVITY_EVENT_ACTIONS.WORKORDER_STARTED,
  ACTIVITY_EVENT_ACTIONS.WORKORDER_CANCELLED,
  ACTIVITY_EVENT_ACTIONS.COMMERCIAL_ACTIVITY_COMPLETED,
  ACTIVITY_EVENT_ACTIONS.CUSTOMER_CREATED,
  ACTIVITY_EVENT_ACTIONS.PROJECT_STARTED,
  ACTIVITY_EVENT_ACTIONS.PROJECT_FINISHED,
  ACTIVITY_EVENT_ACTIONS.PROJECT_CREATED,
  ACTIVITY_EVENT_ACTIONS.ATTENTION_RESOLVED,
  ACTIVITY_EVENT_ACTIONS.ATTENTION_WORKORDER_GENERATED,
  ACTIVITY_EVENT_ACTIONS.REQUEST_RESOLVED,
  ACTIVITY_EVENT_ACTIONS.REQUEST_CREATED,
  LEGACY_CS_ACTIONS.CASE_CLOSED,
  LEGACY_CS_ACTIONS.OT_CREATED,
  LEGACY_CS_ACTIONS.CASE_CREATED,
])

export const EXECUTIVE_RELEVANT_ACTIVITY_LIMIT = 10
